version: '3.3'

services:
  front:
    build:
      context: ./front
    volumes:
      - ./front:/usr/share/nginx/html
    ports:
      - "3000:80"
    depends_on:
      - back

  back:
    build:
      context: ./back
    volumes:
      - ./back:/app
    ports:
      - "8000:8000"
    environment:
      DATABASE_URL: postgresql://postgres:postgres@db:5432/quiz
    depends_on:
      - db

  db:
    image: postgres:latest
    environment:
      POSTGRES_DB: quiz
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres